services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-medods}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-medods}
      POSTGRES_DB: ${POSTGRES_DB:-medods}
    ports:
      - "5432:5432"