definitions:
  api.LoginRequest:
    properties:
      guid:
        example: 12345678-1234-1234-1234-123456789012
        type: string
    required:
    - guid
    type: object
  api.TokenPair:
    properties:
      access_token:
        description: AccessToken is a JWT token that can be used to access the API
        type: string
      refresh_token:
        description: |-
          RefreshToken is a randomly generated base64 string that can be used to refresh the access token
          It is valid for 30 days
          Refresh token can only be used to refresh a single access token it was issued with.
          After refreshing, the refresh token is no longer valid and cannot be used again.
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: do ping
      parameters:
      - description: login request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.TokenPair'
      summary: Generate a token pair from guid
swagger: "2.0"
