// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"net/netip"
	"time"
)

type Auth struct {
	ID               int32      `json:"id"`
	Guid             string     `json:"guid"`
	RefreshTokenHash string     `json:"refresh_token_hash"`
	IpAddress        netip.Addr `json:"ip_address"`
	UserAgent        string     `json:"user_agent"`
	RefreshedAt      time.Time  `json:"refreshed_at"`
	CreatedAt        time.Time  `json:"created_at"`
}
