// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Auth struct {
	ID           int32            `json:"id"`
	Guid         pgtype.UUID      `json:"guid"`
	RefreshToken string           `json:"refresh_token"`
	IpAddress    netip.Addr       `json:"ip_address"`
	UserAgent    string           `json:"user_agent"`
	RefreshedAt  pgtype.Timestamp `json:"refreshed_at"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
